using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ldvdbclasslibrary
{
    public enum AccountType : long
    {
        Administrator = 1,
        Donor = 2,
        Client = 3,
    }

    public enum CustomControllerProtocols : long
    {
        RegisterAccountByRegistrationId = 1000,
        CreateUserAccount = 2000,
        LoginSystemUser = 3000,
        GetSystemUserAccountType = 4000,
        SendPasswordResetEmail = 5000,
        UpdateUserPassword = 6000,
        CreateModuleView = 7000,
        RetrieveIndividualInformation = 8000,
        SaveIndividualInformation = 9000,
        RetrieveAllPrograms = 10000,
        RetrieveProgramEventsByProgram = 11000,
        RetrieveAllAdministrators = 12000,
        AddAdministrator = 13000,
        DeleteAdministrator = 14000,
        RetrieveAllClients = 15000,
        AddClient = 16000,
        ModifyClient = 17000,
        DeleteClient = 18000,
        RetrieveClientInformationByClientID = 19000,
        SaveClientInformation = 20000,
        RetrieveClientsNotInExclusionList = 21000,
        RetrieveClientFatherByClientID = 22000,
        SaveClientFather = 23000,
        RetrieveClientMotherByClientId = 24000,
        SaveClientMother = 25000,
        DoesClientHaveSystemUserAccount = 26000,
        CreateClientSystemUserAccount = 27000,
        RetrieveListOfProgramsClientIsEnlistedIn = 28000,
        RetrieveListOfProgramEventsClientIsEnlistedIn = 29000,
        EnlistClientInProgram = 30000,
        UnenlistClientInProgram = 31000,
        EnlistClientInProgramEvent = 32000,
        UnenlistClientInProgramEvent = 33000,
        RetrieveDonorAssignedClientRequests = 34000,
        RetrieveAllDonors = 35000,
        AddDonor = 36000,
        ModifyDonor = 37000,
        DeleteDonor = 38000,
        RetrieveListOfProgramsDonorIsEnlistedIn = 39000,
        EnlistDonorInProgram = 40000,
        UnenlistDonorFromProgram = 41000,
        RetrieveClientRequestsByProgramId = 42000,
        SendInternalMessage = 43000,
        RetrieveAllInboxMessages = 44000,
        RetrieveDonorInformationByDonorID = 46000,
        SaveDonorInformation = 48000,
        DeactivateClientSystemUserAccount = 50000,
        RetrieveClientProgramsNotEnlistedIn = 52000,
        RetrieveClientProgramEventsNotEnlistedIn = 54000,
        RetrieveDonorProgramsNotEnlistedIn = 56000,
        RetrieveDonorProgramEventsNotEnlistedIn = 58000,
        RetrieveHappyClientPhotos = 60000,
        AddHappyClientPhoto = 62000,
        DeleteHappyClientPhoto = 64000,
        DeactivateClient = 66000,
        RetrieveAllNonCommittedClientRequests = 68000,
        RetrieveAllCommittedClientRequestsByDonorId = 70000,
        DeactivateDonor = 72000,
        SetMessageRecipientMessageRead = 74000,
        RetrieveAllAvailableMessageRecipientsWithExclusionList = 76000,
        RetrieveMessageRecipientByAccountIDAndAccountTypeID = 78000,
        RetrieveNotificationSettingsByAccountIdAndAccountTypeId = 80000,
        SaveNotificationSettingsByAccountIdAndAccountTypeId = 82000,
        RetrieveAllChildrenByParentClientID = 84000,
        RetrieveAllProgramsChildIsEnlistedIn = 86000,
        RetrieveAllNonDonorCommittedClientRequestsByClientIdAndProgramId = 88000,
        RetrieveAllDonorCommittedClientRequestsByClientIdAndProgramId = 90000,
        RetrieveAllNonDonorCommittedClientRequestsByProgramID = 92000,
        RetrieveAllclientRequestsCommittedToByDonorID = 94000,
        RetrieveDisplayAccountByLoggedInUserID = 96000,
        RetrieveWelcomeMessageByLoggedInUserID = 98000,
    }
}
